//------------------------------------------------------------------------
// Copyright(c) 2022 HJ.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"JK-1.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"JK-1 VST3 (64Bit)"
#else
#define stringFileDescription	"JK-1 VST3"
#endif
#define stringCompanyName		"HJ\0"
#define stringLegalCopyright	"Copyright(c) 2022 HJ."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
