//------------------------------------------------------------------------
// Copyright(c) 2022 My Plug-in Company.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "TESTJK-1.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "TESTJK-1 VST3 (64Bit)"
#else
#define stringFileDescription "TESTJK-1 VST3"
#endif
#define stringCompanyName "TEST My Plug-in Company\0"
#define stringLegalCopyright "TEST Copyright(c) 2022 My Plug-in Company."
#define stringLegalTrademarks \
    "TEST VST is a trademark of Steinberg Media Technologies GmbH"
